[platformio]
default_envs = esp32s3

[env]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 8MB
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    bblanchon/ArduinoJson@6.21.5
    boschsensortec/BME68x Sensor library@1.2.40408

[env:esp32s3]

[env:esp32s3_air]
build_flags =
    ${env.build_flags}
    -DQY_ENABLE_AIR=1
